wcd9xxx: fix -Wmisleading-indentation Fixes: sound/soc/codecs/wcd9xxx-mbhc.c:403:4: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation] snd_soc_update_bits(codec, WCD9XXX_A_MAD_ANA_CTRL, ^ sound/soc/codecs/wcd9xxx-mbhc.c:399:3: note: previous statement is here if ((!checkpolling || mbhc->polling_active) && ^
Matches earlier if condition where snd_soc_update_bits() is called for
WCD9XXX_A_MAD_ANA_CTRL and WCD9XXX_A_LDO_H_MODE_1.

This driver doesn't exist for newer SoCs.  This patch is no functional
change.

Bug: 154242577
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I7c9b6cb043de601a4ba973b70ec42b7d6b0a13a7